### PR TITLE
clarify what is being configured and why

### PR DESCRIPTION
**Pull request by taboularasa**
might be nice to do a little more handholding here to make sure it's clear that there are some assumptions about configuration,  as a side note, maybe we just need the api host if the actual api endpoint is not being customized?

### CODE REVIEW

**Comment by lexi-lambda** [comment]
This should go in the Configuration section of the README. Installation is more of a "Quick Start" than full documentation. Maybe put it there and link to it from Installation?

**Comment by taboularasa** [comment]
ok, well what about the side note. it would be nice to have some default assumptions. e.g. no configuration we assume same host and default endpoints. only host specified we assume default api endpoints

**Comment by lexi-lambda** [comment]
Yeah, the default is `/` as a prefix on the same host that the JS is running on. Do you think we should have a different default? Either way, mentioning it makes sense.

**Comment by taboularasa** [comment]
no `/` is fine. I do think it's worth mentioning.

**Comment by taboularasa** [comment]
no emoji :-1:

**Pull request closed without merging**
